name: Build OpenWrt IPK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      arch:
        description: '目标架构'
        required: true
        default: 'aarch64'
        type: choice
        options:
          - 'aarch64'
          - 'x86_64'
          - 'all'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Package IPK via Python
        run: python3 .github/scripts/pack.py "${{ inputs.arch }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mt5700webui-ipk
          path: "*.ipk"
